#!/bin/bash
# https://dri.freedesktop.org/docs/drm/gpu/amdgpu.html#pp-od-clk-voltage

FILE_PERFORMANCE=$(echo /sys/class/drm/card?/device/power_dpm_force_performance_level)
FILE_CLK_VOLTAGE=$(echo /sys/class/drm/card?/device/pp_od_clk_voltage)

[ -f /etc/amdgpu-overclock.cfg ] && . /etc/amdgpu-overclock.cfg

echo "manual" > $FILE_PERFORMANCE

for i in ${!PSTATE[@]}; do
    echo "PSTATE$i: ${PSTATE[$i]}"
    echo "s $i ${PSTATE[$i]}" > $FILE_CLK_VOLTAGE
done

for i in ${!M_PSTATE[@]}; do
    echo "M_PSTATE$i: ${M_PSTATE[$i]}"
    echo "m $i ${M_PSTATE[$i]}" > $FILE_CLK_VOLTAGE
done

echo "c" > $FILE_CLK_VOLTAGE
